// Generates src/lib/generated/thirdPartyNotices.ts: every runtime-bundled npm
// package (the `dependencies` tree — dev tooling is not distributed and not
// listed) plus the bundled fonts, each with its license text. Run via
// `npm run generate:notices` after changing dependencies.
import { readdirSync, readFileSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();

function readPkg(dir) {
  return JSON.parse(readFileSync(join(dir, "package.json"), "utf-8"));
}

function packageDir(name) {
  const dir = join(root, "node_modules", ...name.split("/"));
  return existsSync(join(dir, "package.json")) ? dir : null;
}

function licenseText(dir) {
  for (const file of readdirSync(dir)) {
    if (/^(license|licence|copying)(\.|$)/i.test(file)) {
      try {
        return readFileSync(join(dir, file), "utf-8");
      } catch {
        return null;
      }
    }
  }
  return null;
}

// Transitive walk over runtime dependencies only.
const rootPkg = readPkg(root);
const queue = Object.keys(rootPkg.dependencies ?? {});
const seen = new Set();
const npm = [];
while (queue.length > 0) {
  const name = queue.pop();
  if (seen.has(name)) {
    continue;
  }

  seen.add(name);
  const dir = packageDir(name);
  if (!dir) {
    console.warn(`WARN: ${name} not found in node_modules`);
    continue;
  }

  const pkg = readPkg(dir);
  npm.push({
    name: pkg.name ?? name,
    version: pkg.version ?? "?",
    license: typeof pkg.license === "string" ? pkg.license : "see text",
    text: licenseText(dir) ?? "License text not included in the package — see its repository.",
  });
  queue.push(...Object.keys(pkg.dependencies ?? {}));
}
npm.sort((a, b) => a.name.localeCompare(b.name));

const fontDir = join(root, "src/lib/assets/fonts");
const fonts = [
  {
    name: "Liberation Sans",
    version: "2.x",
    license: "OFL-1.1",
    text: readFileSync(join(fontDir, "LICENSE-Liberation.txt"), "utf-8"),
  },
  {
    name: "Carlito",
    version: "1.x",
    license: "OFL-1.1",
    text: readFileSync(join(fontDir, "LICENSE-Carlito.txt"), "utf-8"),
  },
  {
    name: "DejaVu Sans",
    version: "2.x",
    license: "Bitstream Vera / public domain",
    text: readFileSync(join(fontDir, "LICENSE-DejaVu.txt"), "utf-8"),
  },
];

const header = `// AUTO-GENERATED by scripts/generateNotices.mjs — do not edit by hand.
// Regenerate with \`npm run generate:notices\` after changing dependencies.

export type NoticeEntry = Readonly<{
  name: string;
  version: string;
  license: string;
  text: string;
}>;

`;

const body =
  `export const npmNotices: readonly NoticeEntry[] = ${JSON.stringify(npm, null, 2)};\n\n` +
  `export const fontNotices: readonly NoticeEntry[] = ${JSON.stringify(fonts, null, 2)};\n`;

mkdirSync(join(root, "src/lib/generated"), { recursive: true });
writeFileSync(join(root, "src/lib/generated/thirdPartyNotices.ts"), header + body);
console.log(`wrote ${npm.length} npm packages + ${fonts.length} fonts`);
